#!/bin/bash
#Skript mis küsib kasutajalt ühe täisarvu ja siis ütleb kas arv on paaris või paaritu

arv=$1


jagatis=$(expr $arv % 2 )
if [[ $jagatis -eq 0 ]];
then
	echo "paaris arv"
else
	echo "paaritu arv"
fi
